server:
  port: 9001
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-microservice
          uri: http://localhost:8001/
          predicates:
            - Path=/users/**
        - id: department-microservice
          uri: http://localhost:8002/
          predicates:
            - Path=/departments/**